# Generated by Django 2.0.4 on 2018-04-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='level',
            field=models.CharField(choices=[('u', 'Urgente'), ('i', 'Intermedio'), ('b', 'Bajo')], default='p', max_length=1),
        ),
    ]
